### ISSUE TITLE
site is reporting error 

### ISSUE THREAD

**Issue by silentnoodlemaster** [generoi/wp-genero-gdpr#1]
copied from email:

```
Error Details
=============
An error of type E_ERROR was caused in line 31 of the file /var/www/staging/bar/releases/20190408133707/web/app/plugins/wp-genero-gdpr/src/Gravityforms/ExpireSubmissions.php. Error message: Uncaught Error: Class 'GFAPI' not found in /var/www/staging/bar/releases/20190408133707/web/app/plugins/wp-genero-gdpr/src/Gravityforms/ExpireSubmissions.php:31
Stack trace:
#0 /var/www/staging/bar/releases/20190408133707/web/wp/wp-includes/class-wp-hook.php(286): GeneroWP\GDPR\Gravityforms\ExpireSubmissions->expire_submissions()
#1 /var/www/staging/bar/releases/20190408133707/web/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /var/www/staging/bar/releases/20190408133707/web/wp/wp-includes/plugin.php(531): WP_Hook->do_action(Array)
#3 /var/www/staging/bar/releases/20190408133707/web/wp/wp-cron.php(133): do_action_ref_array('gf_expire_submi...', Array)
#4 {main}
  thrown
```

**Comment by oxyc** [comment]
Hade du Gravityform enabled? Borde nog fixa så de int kastar error men undrar om de va så lätt att de bara int va enabled.
